export default {
  product: {
    name: 'Reedly',
    description:
      "Reedly est une application mobile iOS et Android d'enregistrement vocal destinée aux commerciaux terrain B2B. Elle enregistre les rendez-vous clients en arrière-plan, transcrit l'audio avec plus de 95% de précision, puis génère automatiquement un rapport structuré en 11 sections en moins de 2 minutes. Reedly propose également un Hub web pour les managers, permettant de centraliser les rapports de toute l'équipe et de générer des synthèses territoriales.",
    url: 'https://www.reedly.ai',
    audiences: ['commerciaux terrain B2B', 'directeurs commerciaux', 'sales managers'],
  },

  featureContext: {
    'voice-recording': {
      nameFr: 'Enregistrement vocal de RDV',
      nameEn: 'Meeting Voice Recording',
      descriptionFr: "Enregistrement audio en arrière-plan pendant les rendez-vous terrain. Un seul tap pour démarrer, batterie optimisée, fonctionne hors connexion. L'audio est supprimé après génération du rapport.",
      descriptionEn: 'Background audio recording during field meetings. One tap to start, battery optimized, works offline. Audio is deleted after report generation.',
      keywordsFr: ['enregistrement vocal réunion', 'application enregistrement rendez-vous client', 'enregistrement audio commercial terrain'],
      keywordsEn: ['meeting voice recording app', 'client meeting recording', 'field sales audio recording'],
      relatedIds: ['ai-transcription', 'ai-report', 'speaker-identification'],
    },
    'ai-transcription': {
      nameFr: 'Transcription IA',
      nameEn: 'AI Transcription',
      descriptionFr: "Transcription automatique de l'audio avec plus de 95% de précision. Fonctionne avec les accents, le vocabulaire métier sectoriel, et en environnement bruyant. Modèles Deepgram et Voxtral.",
      descriptionEn: 'Automatic audio transcription with 95%+ accuracy. Works with accents, sector-specific vocabulary, and noisy environments. Deepgram and Voxtral models.',
      keywordsFr: ['transcription automatique réunion', 'transcription IA rendez-vous commercial', 'transcription vocale professionnelle'],
      keywordsEn: ['automatic meeting transcription', 'AI business meeting transcription', 'professional voice transcription'],
      relatedIds: ['voice-recording', 'ai-report', 'speaker-identification'],
    },
    'ai-report': {
      nameFr: 'Rapport structuré IA',
      nameEn: 'AI Structured Report',
      descriptionFr: "Génération automatique d'un rapport structuré en 11 sections à partir de la transcription : résumé exécutif, profil client, besoins, objections, engagements, prochaines étapes, opportunités, risques, recommandations. Export PDF en 1 clic.",
      descriptionEn: 'Automatic generation of an 11-section structured report from the transcript: executive summary, client profile, needs, objections, commitments, next steps, opportunities, risks, recommendations. 1-click PDF export.',
      keywordsFr: ['rapport de visite client automatique', 'compte rendu réunion IA', 'rapport commercial automatisé'],
      keywordsEn: ['automatic client visit report', 'AI meeting report', 'automated sales report'],
      relatedIds: ['ai-transcription', 'voice-recording', 'territory-syntheses'],
    },
    'speaker-identification': {
      nameFr: 'Identification des interlocuteurs',
      nameEn: 'Speaker Identification',
      descriptionFr: "Diarisation : l'IA identifie qui parle dans la conversation et attribue les propos au bon interlocuteur. Distingue commercial et client pour une attribution précise dans le rapport.",
      descriptionEn: 'Diarization: the AI identifies who speaks and attributes statements to the right person. Distinguishes sales rep and client for precise report attribution.',
      keywordsFr: ['identification interlocuteurs réunion', 'diarisation conversation', 'qui parle dans une réunion IA'],
      keywordsEn: ['meeting speaker identification', 'conversation diarization', 'who spoke in a meeting AI'],
      relatedIds: ['ai-transcription', 'ai-report', 'voice-recording'],
    },
    'territory-syntheses': {
      nameFr: 'Synthèses territoriales',
      nameEn: 'Territory Syntheses',
      descriptionFr: "Agrégation automatique des rapports sur une période (semaine, mois, trimestre) en tendances, risques et opportunités priorisés. Vision stratégique du territoire en quelques secondes.",
      descriptionEn: 'Automatic aggregation of reports over a period (week, month, quarter) into prioritized trends, risks, and opportunities. Strategic territory view in seconds.',
      keywordsFr: ['synthèse activité commerciale terrain', 'analyse territoire commercial', 'agrégation rapports commerciaux'],
      keywordsEn: ['field sales activity synthesis', 'sales territory analysis', 'sales report aggregation'],
      relatedIds: ['ai-report', 'manager-hub', 'sales-directives'],
    },
    'manager-hub': {
      nameFr: 'Hub Manager',
      nameEn: 'Manager Hub',
      descriptionFr: "Interface web pour les directeurs commerciaux. Dashboard centralisé avec tous les rapports de l'équipe, synthèses stratégiques, statistiques membres, gestion d'équipe.",
      descriptionEn: 'Web interface for sales directors. Centralized dashboard with all team reports, strategic syntheses, member stats, team management.',
      keywordsFr: ['tableau de bord manager commercial', 'hub directeur commercial', 'pilotage équipe vente terrain'],
      keywordsEn: ['sales manager dashboard', 'commercial director hub', 'field sales team management'],
      relatedIds: ['territory-syntheses', 'ai-assistant', 'sales-directives'],
    },
    'meeting-prep': {
      nameFr: 'Préparation de RDV',
      nameEn: 'Meeting Preparation',
      descriptionFr: "Préparation assistée par IA avant chaque rendez-vous client. L'IA compile l'historique des interactions, les engagements en cours, et les points de vigilance pour que le commercial arrive préparé.",
      descriptionEn: 'AI-assisted preparation before each client meeting. The AI compiles interaction history, ongoing commitments, and key points so the sales rep arrives prepared.',
      keywordsFr: ['préparation rendez-vous client B2B', 'briefing avant RDV commercial', 'préparation visite client IA'],
      keywordsEn: ['B2B client meeting preparation', 'pre-meeting sales briefing', 'AI client visit preparation'],
      relatedIds: ['client-portfolio', 'ai-report', 'voice-recording'],
    },
    'ai-assistant': {
      nameFr: 'Max — Assistant IA Manager',
      nameEn: 'Max — AI Manager Assistant',
      descriptionFr: "Assistant conversationnel IA pour les managers. Posez des questions sur l'activité de l'équipe, obtenez des analyses croisées, créez des directives, planifiez des actions — en langage naturel.",
      descriptionEn: 'AI conversational assistant for managers. Ask questions about team activity, get cross-analyses, create directives, plan actions — in natural language.',
      keywordsFr: ['assistant IA directeur commercial', 'chatbot manager vente', 'IA pilotage équipe commerciale'],
      keywordsEn: ['AI sales director assistant', 'sales manager chatbot', 'AI sales team management'],
      relatedIds: ['manager-hub', 'territory-syntheses', 'sales-directives'],
    },
    'client-portfolio': {
      nameFr: 'Portfolio Client',
      nameEn: 'Client Portfolio',
      descriptionFr: "Gestion du portefeuille client : entreprises, contacts, historique d'interactions. Fiche client auto-enrichie par l'IA à partir des rapports — timeline, besoins agrégés, score relationnel.",
      descriptionEn: 'Client portfolio management: companies, contacts, interaction history. AI-enriched client card from reports — timeline, aggregated needs, relationship score.',
      keywordsFr: ['gestion portefeuille client commercial', 'fiche client enrichie IA', 'suivi client terrain'],
      keywordsEn: ['sales client portfolio management', 'AI-enriched client card', 'field client tracking'],
      relatedIds: ['ai-report', 'meeting-prep', 'manager-hub'],
    },
    'knowledge-base': {
      nameFr: 'Base de connaissances',
      nameEn: 'Knowledge Base',
      descriptionFr: "Base de connaissances vectorielle pour l'organisation. Importez documents, sites web, liens — l'IA les utilise pour enrichir les rapports et répondre aux questions via Max.",
      descriptionEn: 'Vector knowledge base for the organization. Import documents, websites, links — the AI uses them to enrich reports and answer questions via Max.',
      keywordsFr: ['base de connaissances équipe commerciale', 'knowledge base vente B2B', 'documentation commerciale IA'],
      keywordsEn: ['sales team knowledge base', 'B2B sales knowledge base', 'AI sales documentation'],
      relatedIds: ['ai-assistant', 'ai-report', 'manager-hub'],
    },
    'sales-directives': {
      nameFr: 'Directives commerciales',
      nameEn: 'Sales Directives',
      descriptionFr: "Définissez des directives commerciales avec des checkpoints. L'IA évalue automatiquement chaque rapport par rapport aux directives actives et remonte un score de conformité.",
      descriptionEn: 'Define sales directives with checkpoints. The AI automatically evaluates each report against active directives and surfaces a compliance score.',
      keywordsFr: ['directives commerciales équipe', 'pilotage objectifs commerciaux', 'conformité rapports commerciaux IA'],
      keywordsEn: ['sales team directives', 'sales objective management', 'AI sales report compliance'],
      relatedIds: ['manager-hub', 'ai-assistant', 'territory-syntheses'],
    },
  },

  generation: {
    model: 'claude-sonnet-4-5-20250929',
    maxTokens: 8192,
  },

  styleExamples: [
    'src/components/Hero.astro',
    'src/components/Problem.astro',
    'src/components/Features.astro',
  ],
};
